### ISSUE TITLE
.or_raises fails on KeyInspector and ChainInspector objects

### ISSUE THREAD

**Issue by CrazyPython** [kislyuk/ensure#24]
This line:
```python
ensure(data).has_key('config').or_raise(ParameterMismatchError)
```

fails with the error `AttributeError: 'KeyInspector' object has no attribute 'or_raise'`

Generic version:

```python
ensure({1 : 2}).has_key(1).or_raise(TypeError)
```

**Comment by kislyuk** [comment]
This is by design. The point of `or_raise` is that it's used when the exception is deferred. When you use `ensure.ensure()`, the exception is raised immediately on any assertion error, and you have no need to use, or access to `.or_raise()`. To use `.or_raise()`, you have to chain from `ensure.check()`:
```
ensure.check({1 : 2}).has_key(3).or_raise(Exception)
```

**Comment by kislyuk** [comment]
To further clarify, the point of `ensure.check(...).or_raise(exception_type, [exception_args])` is to allow easy control of the kind of exception raised and its arguments.

**Comment by CrazyPython** [comment]
Ah, I understand now. Could this be more well documented?
