### ISSUE TITLE
or_raise(Exception, string) encounters a KeyError when string contains {}

### ISSUE THREAD

**Issue by lakshayg** [kislyuk/ensure#31]
When I pass a string containing `{}` with something in them, to `.or_raise` as the 2nd param, I encounter a `KeyError`. I assume this is because something in `or_raise`/deeper in the call stack that uses `.format` on the string. Since the string contains curly braces which are interpreted as a placeholder, it tries to substitute something in there which is not available to the `.format` call.

This is not a major issue for me since I can change the error_message to not contain the curly braces but it would be great to have support for this within the library

**Reproduction**
```
>>> from ensure import check
>>> error_message = "mydata: {a:1, b:2}"
>>> check(1).is_greater_than(2).or_raise(Exception, error_message)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ensure/main.py", line 742, in or_raise
    raise error_factory(message.format(*args, **kwargs))
KeyError: 'a'
```

**Comment by kislyuk** [comment]
This is done by design to be able to format the error message. Please see https://ensure.readthedocs.io/en/latest/#ensure.Check.or_raise for the documentation. (The API documentation was previously broken, so this docstring did not show up on the doc website.) You can use double curly braces to escape your braces from formatting: `"{{}}"`.
